global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'employee'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['employee:8081']

  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka:8761']
