server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8761/eureka/}
  instance:
    instance-id: balance-instance
spring:
  application:
    name: balance
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
